create extension if not exists pgcrypto;

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz default now()
);

create table if not exists categories (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text,
  created_at timestamptz default now()
);

create table if not exists topics (
  id bigint generated by default as identity primary key,
  category_id bigint references categories(id) on delete cascade,
  name text not null,
  slug text not null,
  description text,
  is_active boolean default true,
  created_at timestamptz default now(),
  unique(category_id, slug)
);

create table if not exists questions (
  id bigint generated by default as identity primary key,
  category_id bigint references categories(id),
  topic_id bigint references topics(id),
  question_text text not null,
  explanation text,
  difficulty text default 'sedang' check (difficulty in ('mudah', 'sedang', 'sulit')),
  status text default 'draft' check (status in ('draft', 'approved', 'published', 'rejected', 'archived')),
  source_type text default 'manual',
  source_url text,
  license text,
  attribution text,
  generated_by_ai boolean default false,
  ai_model text,
  created_by uuid references auth.users(id),
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz,
  published_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists question_options (
  id bigint generated by default as identity primary key,
  question_id bigint references questions(id) on delete cascade,
  label text not null check (label in ('A', 'B', 'C', 'D', 'E')),
  option_text text not null,
  is_correct boolean default false,
  score int default 0,
  created_at timestamptz default now(),
  unique(question_id, label)
);

create table if not exists practice_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  category_id bigint references categories(id),
  topic_id bigint references topics(id),
  status text default 'ongoing' check (status in ('ongoing', 'finished', 'cancelled')),
  total_questions int default 0,
  total_score int default 0,
  started_at timestamptz default now(),
  finished_at timestamptz
);

create table if not exists user_answers (
  id bigint generated by default as identity primary key,
  session_id uuid references practice_sessions(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  question_id bigint references questions(id),
  selected_option_id bigint references question_options(id),
  score int default 0,
  answered_at timestamptz default now(),
  unique(session_id, question_id)
);

create table if not exists session_questions (
  id bigint generated by default as identity primary key,
  session_id uuid references practice_sessions(id) on delete cascade,
  question_id bigint references questions(id) on delete cascade,
  position int not null,
  created_at timestamptz default now(),
  unique(session_id, question_id),
  unique(session_id, position)
);

create table if not exists score_results (
  id bigint generated by default as identity primary key,
  session_id uuid references practice_sessions(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  category_id bigint references categories(id),
  topic_id bigint references topics(id),
  total_questions int,
  answered_questions int,
  correct_count int,
  wrong_count int,
  total_score int,
  created_at timestamptz default now()
);

create table if not exists generation_settings (
  id bigint generated by default as identity primary key,
  category_id bigint references categories(id),
  topic_id bigint references topics(id),
  difficulty text default 'sedang' check (difficulty in ('mudah', 'sedang', 'sulit')),
  min_active_questions int default 30,
  generate_batch_size int default 5,
  auto_publish boolean default false,
  is_enabled boolean default true,
  created_at timestamptz default now()
);

create table if not exists generation_jobs (
  id uuid primary key default gen_random_uuid(),
  trigger_type text not null,
  category_id bigint references categories(id),
  topic_id bigint references topics(id),
  difficulty text check (difficulty in ('mudah', 'sedang', 'sulit')),
  requested_count int default 5,
  status text default 'queued' check (status in ('queued', 'running', 'success', 'failed')),
  error_message text,
  created_by uuid references auth.users(id),
  created_at timestamptz default now(),
  started_at timestamptz,
  finished_at timestamptz
);

create table if not exists question_drafts (
  id bigint generated by default as identity primary key,
  generation_job_id uuid references generation_jobs(id) on delete set null,
  category_id bigint references categories(id),
  topic_id bigint references topics(id),
  question_json jsonb not null,
  status text default 'draft' check (status in ('draft', 'approved', 'published', 'rejected')),
  quality_score int,
  ai_model text,
  created_at timestamptz default now(),
  reviewed_at timestamptz
);

create table if not exists ai_generation_logs (
  id bigint generated by default as identity primary key,
  generation_job_id uuid references generation_jobs(id) on delete set null,
  provider text default 'gemini',
  model text,
  prompt text,
  response_preview text,
  success boolean default false,
  error_message text,
  created_at timestamptz default now()
);

create table if not exists app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz default now()
);

alter table profiles enable row level security;
alter table categories enable row level security;
alter table topics enable row level security;
alter table questions enable row level security;
alter table question_options enable row level security;
alter table practice_sessions enable row level security;
alter table user_answers enable row level security;
alter table session_questions enable row level security;
alter table score_results enable row level security;
alter table generation_settings enable row level security;
alter table generation_jobs enable row level security;
alter table question_drafts enable row level security;
alter table ai_generation_logs enable row level security;
alter table app_settings enable row level security;

drop policy if exists "Users can read their profile" on profiles;
create policy "Users can read their profile" on profiles for select using (auth.uid() = id);
drop policy if exists "Users can update their profile" on profiles;
create policy "Users can update their profile" on profiles for update using (auth.uid() = id);

drop policy if exists "Authenticated users can read categories" on categories;
create policy "Authenticated users can read categories" on categories for select to authenticated using (true);
drop policy if exists "Authenticated users can read topics" on topics;
create policy "Authenticated users can read topics" on topics for select to authenticated using (true);
drop policy if exists "Authenticated users can read published questions" on questions;
create policy "Authenticated users can read published questions" on questions for select to authenticated using (status = 'published');
drop policy if exists "Authenticated users can read published options" on question_options;
create policy "Authenticated users can read published options" on question_options for select to authenticated using (
  exists (select 1 from questions where questions.id = question_options.question_id and questions.status = 'published')
);

drop policy if exists "Users can manage own sessions" on practice_sessions;
create policy "Users can manage own sessions" on practice_sessions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users can manage own answers" on user_answers;
create policy "Users can manage own answers" on user_answers for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users can read own session questions" on session_questions;
create policy "Users can read own session questions" on session_questions for select using (
  exists (
    select 1 from practice_sessions
    where practice_sessions.id = session_questions.session_id
      and practice_sessions.user_id = auth.uid()
  )
);
drop policy if exists "Users can read own scores" on score_results;
create policy "Users can read own scores" on score_results for select using (auth.uid() = user_id);

drop policy if exists "Users can create generation jobs" on generation_jobs;
create policy "Users can create generation jobs" on generation_jobs for insert to authenticated with check (auth.uid() = created_by);
drop policy if exists "Users can read own generation jobs" on generation_jobs;
create policy "Users can read own generation jobs" on generation_jobs for select using (auth.uid() = created_by);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, new.raw_user_meta_data ->> 'full_name')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
